### ISSUE TITLE
如何配置插件

### ISSUE THREAD

**Issue by mingshengxiao** [yoranfu/alpha-scripts#2]
我在使用的过程中，遇到一个需求需要添加webpack插件，使用webpack的话是在plugins里面添加，但是在options里面没有看到有配置plugins的地方，这个需要怎么处理呢

**Comment by yoranfu** [comment]
@mingshengxiao 目前没有暴露plugins的配置入口。能否说明需要添加什么插件？可以考虑看是否需要暴露plugins配置
